name = "StatsProcedures"
uuid = "d2f4e7c0-4966-47f3-9552-d63f8a71a436"
authors = ["Junyuan Chen <norman.chen.git@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
Combinatorics = "1"
MacroTools = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
